### ISSUE TITLE
Upload is done but I can't see the build in app control

### ISSUE THREAD

**Issue by ornakash** [simonnilsson/ios-uploader#10]
8First of all, many thanks for this great tool!!!!! I can't wait to upload my app to app store.

I used the $ ios-uploader -u <username> -p <password> -f <path/to/app.ipa> command and it seems that everything went OK.
Unfortunately when I get to AppConnect and search for the build I don't see anything:

![image](https://user-images.githubusercontent.com/45389557/108328083-daa23100-71d4-11eb-9e9e-cf74127a1ec8.png)

What did I do wrong? :(

**Comment by ornakash** [comment]
I just had to wait! it works perfectly. Many thanks!

**Comment by simonnilsson** [comment]
@ornakash Yes it usally takes a short time before it is visible in Apples interface because they do some initial automated checks on the uploaded package. 

Note that your password is visible in your screenshot, if you have not already done so you should probably revoke that password.
