### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by OsamaMohammed** [simonnilsson/ios-uploader#13]
Recently I faced this problem when trying to upload IPA file.
I think apple changed their API URLs ?

Request failed with status code 404

**Comment by simonnilsson** [comment]
Hi. I don't believe so. Could it have been a temporary outage? Looks like they are doing some maintenance on their services at the moment.

**Comment by OsamaMohammed** [comment]
I tested it just now and it works fine, as you said @simonnilsson its mostly maintenance. Thanks.
