### ISSUE TITLE
Failed to extract Bundle ID and version, are you supplying a valid IPA-file?

### ISSUE THREAD

**Issue by SalavatR** [simonnilsson/ios-uploader#14]
Hello!
got error "Failed to extract Bundle ID and version, are you supplying a valid IPA-file?"
file size 463mb

**Comment by simonnilsson** [comment]
Hi, if you could send me a link to your IPA-file I could try to localize the issue.
simonnilsson@altmails.com

**Comment by SalavatR** [comment]
found issue, new apple payment polytic wasn't agreed by account ouwner, sorry
