### ISSUE TITLE
Upload from URL

### ISSUE THREAD

**Issue by brnyza** [simonnilsson/ios-uploader#16]
Is it possible to upload from URL like this?

`ios-uploader -u aaa@bbb.com -p aaaa-bbbb-cccc-dddd -f "https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/test-archive.ipa"`

**Comment by simonnilsson** [comment]
Only files on the local filesystem are supported atm. But will consider implementing it as a new feature as I can see the uses for it.

**Comment by simonnilsson** [comment]
Implemented in v1.5.0

Note that the file will still be downloaded to a temporary directory on the local system for pre-processing. So might lead to a slightly longer delay at start of upload process depending on file size. But should simplify the process by avoiding having to manually download the file.
