### ISSUE TITLE
Two Factor login error

### ISSUE THREAD

**Issue by olavomello** [simonnilsson/ios-uploader#17]
Dude,

amazing solution. But my login have a two-factor and I'm not able to login.
I don't know if this is the problem but the question is, I can't proceed with access.

Any idea ?

Thank you so much and great job !

**Comment by simonnilsson** [comment]
Hi, you need to create an app-specific password, it is in the README.

> See this page for information on how to generate an app specific password:
> https://support.apple.com/en-us/HT204397

**Comment by olavomello** [comment]
Yes, Simon. I´ve tried and works. Thank you so much. 
Awesome work dude!
