### ISSUE TITLE
upload failed with socket hang up 

### ISSUE THREAD

**Issue by lanx19** [simonnilsson/ios-uploader#19]
meet this situation while uploading my app with version 2.0

**Comment by simonnilsson** [comment]
Hi @lanx19. This sounds like an issue with your network connection. Was this a one time thing or do you get this error repeatedly?

**Comment by lanx19** [comment]
I got the error repeatedly, so I used Apple transporter to do the same thing after generated _AppstoreInfo.plist_.

**Comment by lanx19** [comment]
It works fine now
