### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by Badisi** [simonnilsson/ios-uploader#2]
### Issue

I've been trying your package on macOS and got the following issue:
```
> yarn global add ios-uploader
> ios-uploader
> env: node\r: No such file or directory
```
It relates to the file `/bin/cli.js` that is using CRLF line endings.
=> CRLF are a Windows thing whereas Unix/macOS are using LF.

**npm** seems to auto fix it depending on the OS : https://github.com/npm/npm/issues/12371
**yarn** (which I'm using..) doesn't : https://github.com/yarnpkg/yarn/issues/5480

### Possible workaround

Configuring your **git** : [configuring-git-to-handle-line-endings](https://docs.github.com/en/enterprise/2.20/user/github/using-git/configuring-git-to-handle-line-endings).
And also making `/bin/cli.js` a real executable (by convention it should be `/bin/cli`, without file extension)

**Comment by simonnilsson** [comment]
Hi @Badisi, thank you for reporting the issue and suggested fixes. 

I will fix the line endings asap. I do however prefer to keep the .js extension for cli.js to allow it to be properly identified by editors and so on, I don't think it should cause a problem.

**Comment by simonnilsson** [comment]
Line endings fixed. Tested and working with yarn now.

**Comment by Badisi** [comment]
Hi @simonnilsson, thanks for your responsiveness and for the fix !

I also have one or two improvements I would like to suggest if you don't mind.
I will create them later today.
Thanks again :-)
