### ISSUE TITLE
Getting the error " make sure you are signed into Xcode with an Apple ID"

### ISSUE THREAD

**Issue by amartya-dev** [simonnilsson/ios-uploader#20]
No suitable application records were found. Verify your bundle identifier is correct and that you are signed into Xcode with an Apple ID that has access to the app in App Store Connect. (1190)

**Comment by simonnilsson** [comment]
Hi. Have you created an app in App Store Connect with a matching Bundle ID? And does the user account used for uploading have full permissions?

**Comment by simonnilsson** [comment]
Lacks info to progress with this issue. Likely not caused by ios-uploader.
