### ISSUE TITLE
Uncaught Syntax Error

### ISSUE THREAD

**Issue by CoralStar** [simonnilsson/ios-uploader#22]
When typing out the following, with correct info, it returns this when I type out the file path:
`$ ios-uploader -u <username> -p <password> -f <path/to/app.ipa>`
`Uncaught SyntaxError: Unexpected identifier`

I am on Windows and recently tried to use it for my .ipa file.
Another example would be appreciated.

**Comment by simonnilsson** [comment]
Hi @CoralStar. Are you using the executable or the npm package? In case of the npm package, what node version are you running? Also what terminal application are you using?

Does it run without errors if you run just `ios-uploader -h`? It might be some special character in your username/password/path that fails to parse as an argument.

**Comment by simonnilsson** [comment]
Lacking required information to take this further.  Closing the  issue.
