### ISSUE TITLE
feat: add version validation

### ISSUE THREAD

**Issue by Badisi** [simonnilsson/ios-uploader#4]
### Improvement

Actually, if I'm trying to upload a binary which was already uploaded, your package gives no error but yet I'm receiving an email from Apple saying:
> ITMS-90189: Redundant Binary Upload - You've already uploaded a build with build number '15' for version number '1.2.1'

So it would be great to have a pre-validation of the version before submission 🙂

**Comment by simonnilsson** [comment]
This should be possible to implement. I believe altool does this check.

**Comment by Badisi** [comment]
Yes it does ;-)

> Package Summary:
> 1 package(s) were not uploaded because they had problems:
> 
> /var/folders/mt/dhwsmtwx7m3b9f3g4ywgdcxw0000gp/T/EA407B2F-539E-4676-A37D-A28B668B8A0A/1527121365.itmsp - Error Messages: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '15' for version number '1.2.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
> 
> 2020-08-26 14:34:04.659 altool[81280:5948713] *** Error: Errors uploading 'platforms/ios/build/device/app - DEV.ipa': ("Error Domain=ITunesTransporterErrorDomain Code=-18000 \"ERROR ITMS-90189: \"Redundant Binary Upload. You've already uploaded a build with build number '15' for version number '1.2.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).\"\" UserInfo={NSLocalizedRecoverySuggestion=ERROR ITMS-90189: \"Redundant Binary Upload. You've already uploaded a build with build number '15' for version number '1.2.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).\", NSLocalizedDescription=ERROR ITMS-90189: \"Redundant Binary Upload. You've already uploaded a build with build number '15' for version number '1.2.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).\", NSLocalizedFailureReason=ERROR ITMS-90189: \"Redundant Binary Upload. You've already uploaded a build with build number '15' for version number '1.2.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).\"}"

**Comment by simonnilsson** [comment]
Took a while to figure out what altool did differently, but found that they sent some more data along in the metadata.xml file, the version strings in particular. After this addition you now get the "Redundant Binary Upload" in the validate metadata stage. And after the fix in #3 this error will be logged to the user.

Thanks for the input @Badisi !
