### ISSUE TITLE
ITMS-90345: Metadata/Info.plist Mismatch

### ISSUE THREAD

**Issue by Badisi** [simonnilsson/ios-uploader#5]
### Issue

I got the following issue from Apple after trying **ios-uploader@1.1.0**:
> ITMS-90345: Metadata/Info.plist Mismatch - The value for bundle_short_version_string in the metadata.xml file does not match the value for CFBundleShortVersionString in app - DEV [Payload/app - DEV.app].

### Fix

`index.js - line 37`
```js
 .replace('BUNDLE_SHORT_VERSION', ctx.bundleVersion) // <-- this should be ctx.bundleShortVersion
 .replace('BUNDLE_VERSION', ctx.bundleVersion)
```

I would also change the following log in order to have something like `X.X.X (XX)` (ie. version (build)):

`cli.js - line 38`
```js
console.log(`Found Bundle ID "${ctx.bundleId}", Bundle Version ${ctx.bundleShortVersion} (${ctx.bundleVersion}).`);
```

**Comment by Badisi** [comment]
Except this last issue, everything is working fine !
So a big thank you 👏

**Comment by simonnilsson** [comment]
You are absolutely right, an autocomplete typo on my part probably.

Good suggestion on modifying the message.

**Comment by simonnilsson** [comment]
Fixed.
