### ISSUE TITLE
Commit reservation failed! Unable to process the request. Please try again or use a different transport. (1360)

### ISSUE THREAD

**Issue by SalavatR** [simonnilsson/ios-uploader#7]
I tryed from windows and linux and got error:

:~$ ios-uploader -u "asd@asd.asd" -p "asdf-asdf-asdf-asdf" -f build.ipa
Found Bundle ID "com.asdffadsf.asdffff.ios", Version 0 (21.0).
Identified application as "My app" (1111111111).
Uploading |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% | 525/332610567 bytes | ETA: INFs | Speed: 210 B/s
Commit reservation failed!
Unable to process the request. Please try again or use a different transport. (1360)

**Comment by simonnilsson** [comment]
Hi, I'm not sure of the cause of this error. The error is displayed as returned from Apple. 

If you have tried on two different operating systems i suspect it might be something about your ipa causing the error. Is **0** your real version number? That might be an issue.

**Comment by simonnilsson** [comment]
Might also be a network/connection issue.

**Comment by SalavatR** [comment]
hello, thanks for responce!
from xcode and App Uploader this ipa works fine, but your program inspires more confidence
I'll check it after new year hollydays

**Comment by simonnilsson** [comment]
When you test it again please use the latest release where I have improved the error handling of failed uploads. It should hopefully give a better error message.

Happy holidays.

**Comment by jtiret** [comment]
Hi @simonnilsson 👋

Just got the same error as @SalavatR. I updated the package as you suggested and then the error message was clearer:

> Upload failed!
> Request body larger than maxBodyLength limit

I suspected that it was due to the size of the IPA being larger. The IPA was indeed larger than usual, but it works fine with the Transporter app. 

Have you seen errors like that in the past?

**Comment by simonnilsson** [comment]
Hi @jtiret 

Interesting, I have never tried IPAs that big. Now that I have more to go on I can investigate. I will look into it.

**Comment by simonnilsson** [comment]
I believe this issue has been solved in the latest update, please reopen if that is not the case.
