### ISSUE TITLE
error try to do an upload

### ISSUE THREAD

**Issue by gabrielcarnez** [simonnilsson/ios-uploader#9]
I used the library a months ago and everything was fine to upload  my app, but I try to made an update this week and I have the next error, I try to find if it's a problem with my npm but I don't know :/ 

thanks!!!

AppData\Roaming\npm\node_modules\ios-uploader\node_modules\simple-plist\simple-plist.js:20
    throw new Error(error)
    ^

Error: Error: maxObjectCount exceeded

**Comment by simonnilsson** [comment]
Hi, this is an error given by one of the applications dependencies. I believe it's something about the Info.plist in your ipa-file it doesn't agree with. If you would be willing to send over your .ipa I might be able to troubleshoot it.

**Comment by gabrielcarnez** [comment]
Hi Simon, yes, you have the right, my apologies, I Don't not why I not saw that, I was thiking that it was a mistakes with some npm depencency! thanks! I will try to fix by my own! have a nice day, week, month etc

**Comment by TheXRMonk** [comment]
> Hi, this is an error given by one of the applications dependencies. I believe it's something about the Info.plist in your ipa-file it doesn't agree with. If you would be willing to send over your .ipa I might be able to troubleshoot it.

Have similar issue - can you explain what I have to do to fix this?

**Comment by simonnilsson** [comment]
@VirsabiMunk This error i thrown by the[ joeferner/node-bplist-parser](https://github.com/joeferner/node-bplist-parser/) module. This is if your Info.plist file contains more than the default limit of 32768 objects. This file usually only contains around 260 objects. 

It might also be that there is nothing wrong with your Info.plist but that the wrong file is identified as your main Info.plist in the IPA. But without having an IPA file showing the issue it is difficult for me to troubleshoot.

**Comment by simonnilsson** [comment]
As I don't have anything to go on in order to resolve this issue I will close it for now. If someone still encounters this issue and can give me a way to reproduce it please reopen the issue.
